/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import LIB.FadeEffect;
import static Module.MainFrame.tablemembers;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class AddBooks extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
   
       DefaultTableModel model = new DefaultTableModel();
       
    public AddBooks() {
        initComponents();
         conn=JavaConnector.ConnectDb();
    
        
        ImageIcon ic = new ImageIcon(getClass().getResource("/Module/icons8_Library_100px.png"));
        this.setIconImage(ic.getImage());
        
         BookID();
    }
//==================================================================================================
 public final void Bookstbl() {
      try{
            String sql = "SELECT * FROM books ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            MainFrame.tablebooks.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
 }          
//================================================================================================== 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BookID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Category = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Author = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Edition = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Publisher = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TotalBooks = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Books");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(850, 530));
        setMinimumSize(new java.awt.Dimension(850, 530));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        jLabel1.setText("Book ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        BookID.setEditable(false);
        BookID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BookID.setForeground(new java.awt.Color(204, 0, 0));
        BookID.setOpaque(false);
        jPanel1.add(BookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 40));

        jLabel2.setText("Book Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 40));

        BookName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BookName.setOpaque(false);
        jPanel1.add(BookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 280, 40));

        jLabel3.setText("Category");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 40));

        Category.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Category.setOpaque(false);
        jPanel1.add(Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 280, 40));

        jLabel4.setText("Author");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 40));

        Author.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Author.setOpaque(false);
        jPanel1.add(Author, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 280, 40));

        jLabel5.setText("Edition");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 40));

        Edition.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Edition.setOpaque(false);
        jPanel1.add(Edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 280, 40));

        jLabel6.setText("Publisher");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 40));

        Publisher.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Publisher.setOpaque(false);
        jPanel1.add(Publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 280, 40));

        jLabel7.setText("Total Books");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 90, 40));

        TotalBooks.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TotalBooks.setOpaque(false);
        jPanel1.add(TotalBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 210, 40));

        jLabel8.setText("Book Type");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 90, 40));

        Price.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Price.setOpaque(false);
        jPanel1.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 210, 40));

        jLabel10.setText("Price");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 90, 40));

        jDateChooser1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 210, 40));

        jLabel9.setText("Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 90, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=SELECT=", "Borrow", "Read Only" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 210, 40));

        jLabel11.setText("ISBN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 90, 40));

        ISBN.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ISBN.setOpaque(false);
        jPanel1.add(ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 210, 40));

        jLabel12.setText("Year");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 90, 40));

        Year.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Year.setOpaque(false);
        jPanel1.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 820, 10));

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Add_New_35px.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 140, 50));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Close-2-icon.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         int x = evt.getXOnScreen();
         int y = evt.getYOnScreen();
         this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged
int xx,xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(x==0){  
        
        try{
            String sql = "INSERT INTO books" 
             +"(BookID, BookName, Category, Author, Edition, Publisher, Date, BookType, TotalBooks, Price, ISBN, Year, Marks)"
             +"values(?,?,?,?,?,?,?,?,?,?,?,?,0)";
            pst = conn.prepareStatement(sql);
            pst.setString(1,BookID.getText());
            pst.setString(2,BookName.getText());
            pst.setString(3,Category.getText());
            pst.setString(4,Author.getText());
            pst.setString(5,Edition.getText());
            pst.setString(6,Publisher.getText());
            pst.setString(7,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
            pst.setString(8, jComboBox1.getSelectedItem().toString());
            pst.setString(9,TotalBooks.getText());
            pst.setString(10,Price.getText());
            pst.setString(11,ISBN.getText());
            pst.setString(12,Year.getText());
            pst.executeUpdate();
           model.setRowCount(0);
           Bookstbl();
            
            JOptionPane.showMessageDialog(this,"Save Successfull !");     
            this.dispose();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this,e);       
          }
        }  
    }//GEN-LAST:event_jButton2ActionPerformed
//==================================================================================================
    public void BookID() {
     try {
         String sql = "SELECT BookID FROM books ORDER BY BookID DESC LIMIT 1";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if(rs.next())
         {
             String rnno = rs.getString("BookID");
             int co = rnno.length();
             String txt = rnno.substring(0, 2);
             String num = rnno.substring(2, co);
             int n = Integer.parseInt(num);
             n++;
             String snum=Integer.toString(n);
             String ftxt=txt+snum;
             BookID.setText(ftxt);
         }else{
             BookID.setText("111");
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, e);
     }
 }
//==================================================================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                   UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Author;
    private javax.swing.JTextField BookID;
    private javax.swing.JTextField BookName;
    private javax.swing.JTextField Category;
    private javax.swing.JTextField Edition;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Publisher;
    private javax.swing.JTextField TotalBooks;
    private javax.swing.JTextField Year;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
