/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import static Module.UpdateMembers.updatetable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jayjomjohn
 */
public class UpdateBook extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
   
       DefaultTableModel model = new DefaultTableModel();
       
    public UpdateBook() {
        initComponents();
         conn=JavaConnector.ConnectDb();
         
        ImageIcon ic = new ImageIcon(getClass().getResource("/Module/icons8_Library_100px.png"));
        this.setIconImage(ic.getImage());
      
    }
//==================================================================================================
 public final void Bookstbl() {
      try{
            String sql = "SELECT * FROM books ";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            MainFrame.tablebooks.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){        
        }
 }          
//================================================================================================== 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        w1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        w2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        w3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        w4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        w5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        w6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        w9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        w10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        w7 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        w8 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        w11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        w12 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UpdateBooks");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(850, 530));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        jLabel1.setText("Book ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 40));

        w1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w1.setForeground(new java.awt.Color(204, 0, 0));
        w1.setOpaque(false);
        w1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                w1KeyReleased(evt);
            }
        });
        jPanel1.add(w1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 40));

        jLabel2.setText("Book Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 40));

        w2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w2.setForeground(new java.awt.Color(0, 0, 0));
        w2.setOpaque(false);
        jPanel1.add(w2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 280, 40));

        jLabel3.setText("Category");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 40));

        w3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w3.setForeground(new java.awt.Color(0, 0, 0));
        w3.setOpaque(false);
        jPanel1.add(w3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 280, 40));

        jLabel4.setText("Author");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 40));

        w4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w4.setForeground(new java.awt.Color(0, 0, 0));
        w4.setOpaque(false);
        jPanel1.add(w4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 280, 40));

        jLabel5.setText("Edition");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 40));

        w5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w5.setForeground(new java.awt.Color(0, 0, 0));
        w5.setOpaque(false);
        jPanel1.add(w5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 280, 40));

        jLabel6.setText("Publisher");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 40));

        w6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w6.setForeground(new java.awt.Color(0, 0, 0));
        w6.setOpaque(false);
        jPanel1.add(w6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 280, 40));

        jLabel7.setText("Total Books");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 90, 40));

        w9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w9.setForeground(new java.awt.Color(0, 0, 0));
        w9.setOpaque(false);
        jPanel1.add(w9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 210, 40));

        jLabel8.setText("Book Type");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 90, 40));

        w10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w10.setForeground(new java.awt.Color(0, 0, 0));
        w10.setOpaque(false);
        jPanel1.add(w10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 210, 40));

        jLabel10.setText("Price");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 90, 40));

        w7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(w7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 210, 40));

        jLabel9.setText("Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 90, 40));

        w8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=SELECT=", "Borrow", "Read Only" }));
        jPanel1.add(w8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 210, 40));

        jLabel11.setText("ISBN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 90, 40));

        w11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w11.setForeground(new java.awt.Color(0, 0, 0));
        w11.setOpaque(false);
        jPanel1.add(w11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 210, 40));

        jLabel12.setText("Year");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 90, 40));

        w12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        w12.setForeground(new java.awt.Color(0, 0, 0));
        w12.setOpaque(false);
        jPanel1.add(w12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 820, 10));

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Edit_File_35px.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 140, 50));

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Close-2-icon.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged
int xx,xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
                    xx = evt.getX();
                    xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void w1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w1KeyReleased
       try{
          String sql = "SELECT * FROM books where BookID=?";
          pst=conn.prepareCall(sql);
          pst.setString(1,w1.getText());
          rs = pst.executeQuery();
           
            if(rs.next()) { 
             w1.setText(rs.getString("BookID"));
             w2.setText(rs.getString("BookName"));
             w3.setText(rs.getString("Category"));
             w4.setText(rs.getString("Author"));
             w5.setText(rs.getString("Edition"));
             w6.setText(rs.getString("Publisher"));
             ((JTextField)w7.getDateEditor().getUiComponent()).setText(rs.getString("Date"));
             w8.setSelectedItem(rs.getString("BookType"));
             w9.setText(rs.getString("TotalBooks"));
             w10.setText(rs.getString("Price"));
             w11.setText(rs.getString("ISBN"));
             w12.setText(rs.getString("Year"));            
          }else{               
                w2.setText("");
                w3.setText("");
                w4.setText("");
                w5.setText("");
                w6.setText("");
                ((JTextField)w7.getDateEditor().getUiComponent()).setText(null);
                w8.setSelectedIndex(0);
                w9.setText("");
                w10.setText("");
                w11.setText("");
                w12.setText("");
            }       
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_w1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
       int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Update Record?","Update",JOptionPane.YES_NO_OPTION);     
  if(x==0){
      try { 
        String value = w1.getText();
        String sql ="UPDATE books SET bookid=?, "
                + "bookname=?, "
                + "category=?, "
                + "author=?, "
                + "edition=?, "
                + "publisher=?, "
                + "Date=?,"
                + "Booktype=?, "
                + "totalbooks=?, "
                + "price=?,"
                + "ISBN=?,"
                + "Year=? where BookID="+value;
          pst=conn.prepareStatement(sql);
           
            pst.setString(1,w1.getText());
            pst.setString(2,w2.getText());
            pst.setString(3,w3.getText());
            pst.setString(4,w4.getText());
            pst.setString(5,w5.getText());
            pst.setString(6,w6.getText());
            pst.setString(7,((JTextField)w7.getDateEditor().getUiComponent()).getText());
            pst.setString(8, w8.getSelectedItem().toString());
            pst.setString(9,w9.getText());
            pst.setString(10,w10.getText());
            pst.setString(11,w11.getText());
            pst.setString(12,w12.getText());
               
            pst.executeUpdate(); 
            model.setRowCount(0);
            Bookstbl() ;
       
            JOptionPane.showMessageDialog(null, "Books information has been Updated!");
            this.dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
  }
    }//GEN-LAST:event_jButton2ActionPerformed
//==================================================================================================
 
//==================================================================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             /*   if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
                   UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField w1;
    private javax.swing.JTextField w10;
    private javax.swing.JTextField w11;
    private javax.swing.JTextField w12;
    private javax.swing.JTextField w2;
    private javax.swing.JTextField w3;
    private javax.swing.JTextField w4;
    private javax.swing.JTextField w5;
    private javax.swing.JTextField w6;
    private com.toedter.calendar.JDateChooser w7;
    private javax.swing.JComboBox<String> w8;
    private javax.swing.JTextField w9;
    // End of variables declaration//GEN-END:variables
}
